services:
  - type: web
    name: garvey
    env: python
    repo: https://github.com/getmagistrate/garvey.git
    region: ohio
    plan: starter
    buildCommand: "make build"
    startCommand: "make daemon"
    envVars:
      - key: ZULIP_BOT_KEY
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: RENDER_WEB_SERVICE_ID
        sync: false
      - key: RENDER_CELERY_SERVICE_ID
        sync: false
      - key: PLAINHOOK_BASE_URL
        sync: false
