services:
  - type: web
    name: garvey
    env: python
    repo: https://github.com/getmagistrate/garvey.git
    region: ohio
    plan: starter
    buildCommand: "make build && mkdir -p /opt/garvey-disk/data"
    startCommand: "make daemon"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.8"
      - key: BOT_DATA_DIR
        value: /opt/garvey-disk/data
      - key: ZULIP_BOT_KEY
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: RENDER_WEB_SERVICE_ID
        sync: false
      - key: RENDER_CELERY_SERVICE_ID
        sync: false
      - key: PLAINHOOK_BASE_URL
        sync: false
    disk:
      name: garvey-disk
      mountPath: /opt/garvey-disk
      sizeGB: 1