services:
  - type: web
    name: garvey
    env: python
    repo: https://github.com/getmagistrate/garvey.git
    region: ohio
    plan: starter
    buildCommand: "make all"
    startCommand: "make run"
    envVars:
      - key: PYTHON_VERSION
        value: "3.8.10"
      - key: ZULIP_BOT_KEY
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: RENDER_WEB_SERVICE_ID
        sync: false
      - key: RENDER_CELERY_SERVICE_ID
        sync: false
      - key: PLAINHOOK_BASE_URL
        sync: false
      - key: WEBSERVER_HTTP_PORT
        value: 80
      - key: WEBSERVER_HTTPS_PORT
        value: 443